### PR TITLE
Add some needed fields to template

### PR DESCRIPTION
**Pull request by itcrab**
I added two fields to default user template:
- headline: set headline for this block (plugin);
- media_link_text: set text for media link eq. "See on Instagram".

### CODE REVIEW

**Comment by itcrab** [comment]
@mishbahr hi again) I add little functionality for more customizing

Please merge this PR

**Comment by itcrab** [comment]
@mishbahr ping

**Comment by mishbahr** [comment]
I'm not sure whether it's necessary to add those as fields.. especially media link text. That could be handled template level. Also you only added migration files for Shango. How about south migrations? While I'm happy to drop support for older version of django.. we need to update setup files to indicate that.

**Comment by itcrab** [comment]
@mishbahr please see my comments

>I'm not sure whether it's necessary to add those as fields.. especially media link text. That could be handled template level.

In current PR general idea is add functionality to set any headline text and media link text in Django-CMS frontend editing plugin on page without any editing files "by hand". We add plugin on page and may edit this text in any time. If we don't needed this - we just don't set this text. Very simple.

>Also you only added migration files for Shango. How about south migrations? While I'm happy to drop support for older version of django.. we need to update setup files to indicate that.

South is so oldest... I add all that needed for current Django release. If someone used oldest versions  Django (when migrations was be only with South) - this problem will be fixed developer in new PR with new issue.

I like you don't have more time for solve all problems with oldest version packages. This PR fine works in current versions packages and it all for need us. You as main contributor may drop oldest versions packages and bump version for `djangocms-instagram`.

**Comment by itcrab** [comment]
@mishbahr ping

**Pull request closed without merging**
